// React/src/App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import React from 'react';
import './App.css';
import { data } from "./data";

import DataGrid, { Editing, Column, GroupPanel, GroupItem, TotalItem, FilterRow, Summary } from "devextreme-react/data-grid";
import {exportDataGrid} from "devextreme/excel_exporter";
import notify from "devextreme/ui/notify";
import DataSource from 'devextreme/data/data_source';
import ArrayStore from 'devextreme/data/array_store';

import * as ExcelJS from "exceljs";

const dataSource = new DataSource({
    store: new ArrayStore({
        data: data,
        key: "ID"
    })
});

class App extends React.Component {
    constructor(props) {
        super(props);
        this.gridRef = React.createRef();

        this.copyViaExcelExport = this.copyViaExcelExport.bind(this);
        this.toolbarCopy = this.toolbarCopy.bind(this);
    }

    rowCopy(e) {
        let data = e.row.data;
        let str = "";

        for (let prop in data) {
            if (data[prop] !== undefined) {
                str += `${data[prop]}\t`;
            }
        }

        navigator.clipboard.writeText(str).then(() => {
            notify("Row data copied to clipboard.", "success", 500);
        }, () => {
            notify("Row data was not copied. There are insufficient permissions for this action.", "error", 500);
        });
    }

    toolbarCopy(e) {
        e.toolbarOptions.items.push({
            widget: "dxButton",
            location: "after",
            options: {
                hint: "Copy via Export",
                icon: "unselectall",
                onClick: this.copyViaExcelExport
            }
        });
    }

    copyViaExcelExport(e) {
        let workbook = new ExcelJS.Workbook();
        let sheet = workbook.addWorksheet("dummy");
        let str = "";

        let col = this.grid.getVisibleColumns();
        // keep exportable columns and get the last-most column
        col = col.filter((x) => x.dataField !== undefined && x.allowExporting === true);
        let lastColumn = col[col.length - 1].dataField;

        exportDataGrid({
            component: this.grid,
            worksheet: sheet,
            customizeCell: function (options) {
                let { gridCell } = options;
                let field = gridCell.column.dataField;

                switch (gridCell.rowType) {
                    // export header row
                    case "header":
                        str += `${gridCell.column.caption}\t`;
                        break;
                    // export data row
                    case "data":
                        str += `${gridCell.value}\t`;
                        break;
                    // export group row
                    case "group":
                        if (gridCell.value)
                            str += `${field}: ${gridCell.value} `;
                        
                        if (gridCell.groupSummaryItems !== undefined && gridCell.groupSummaryItems.length >= 1) {
                            gridCell.groupSummaryItems.forEach(x => {
                                str += ` ${x.name}: ${x.value} `;
                            });
                        }

                        str += `\t`;

                        break;
                    // export groupFooter & totalFooter. Create a separate switch case if you need different actions (ie different spacing)
                    case "groupFooter":
                    case "totalFooter":
                        str += (gridCell.value === undefined ? `\t` : `${gridCell.totalSummaryItemName}: ${gridCell.value}\t`);

                        break;
                    default:
                        console.log("Unknown row type detected. Please check possible DataGrid breaking changes regarding rowType", gridCell);

                        break;
                }

                if (field === lastColumn) {
                    str += `\r\n`;
                }
            }
        }).then(() => {
            console.log(str);
            navigator.clipboard.writeText(str).then(() => {
                notify("Grid data copied to clipboard.", "success", 500);
            }, () => {
                notify("Grid data was not copied. There are insufficient permissions for this action.", "error", 500);
            });
        });
    }
    
    get grid() {
        return this.gridRef.current.instance;
    }

    render() {
        return (
            <DataGrid
                ref={this.gridRef}
                allowColumnResizing={true}
                dataSource={dataSource}
                onToolbarPreparing={this.toolbarCopy}>
                <Column dataField="ID" width={200} />
                <Column dataField="FirstName" />
                <Column dataField="LastName" />
                <Column dataField="HireDate" />
                <Column dataField="Residence" groupIndex={0} />
                <Column dataField="IsTested" />
                <Column type="buttons"
                    buttons={["edit", "delete", {
                        hint: "Copy row",
                        icon: "copy",
                        onClick: this.rowCopy
                    }]} />
                <Editing 
                        mode="popup"
                        allowAdding={true}
                        allowUpdating={true}
                        allowDeleting={true}
                        useIcons={true}
                        />
                <FilterRow visible={true} />
                <GroupPanel visible={true} />

                <Summary>
                    <GroupItem 
                        column="LastName" 
                        summaryType="count"
                        name="Count"
                        alignByColumn={true} />
                    <GroupItem 
                        column="LastName" 
                        summaryType="count"
                        name="Count" />
                    <GroupItem 
                        column="IsTested" 
                        summaryType="count"
                        showInGroupFooter={true}
                        name="Count"
                        alignByColumn={true} />
                    <TotalItem
                        column="ID"
                        summaryType="count"
                        displayFormat={'No. of employees: {0}'}
                        name="No. of employees" />
                    <TotalItem
                        column="HireDate"
                        summaryType="count"
                        name="Dates" />
                </Summary>
            </DataGrid>
        );
    }
}

export default App;

// Vue/src/App.vue
<template>
  <DxDataGrid
    :ref="gridRef"
    :data-source="dataSource"
    :allow-column-resizing="true"
    @toolbar-preparing="toolbarCopy"
  >
    <DxColumn data-field="ID" :width="200" />
    <DxColumn data-field="FirstName" />
    <DxColumn data-field="LastName" />
    <DxColumn data-field="HireDate" />
    <DxColumn data-field="Residence" :group-index="0" />
    <DxColumn data-field="IsTested" />
    <DxColumn type="buttons" :buttons="buttons" />

    <DxEditing
      mode="popup"
      :allow-updating="true"
      :allow-deleting="true"
      :allow-adding="true"
      :use-icons="true"
    />
    <DxGroupPanel :visible="true" />
    <DxFilterRow :visible="true" />
    <DxSummary>
      <DxGroupItem
        column="LastName"
        summary-type="count"
        name="Count"
        :alignByColumn="true"
      />
      <DxGroupItem column="LastName" summary-type="count" name="Count" />
      <DxGroupItem
        column="IsTested"
        summary-type="count"
        :show-in-group-footer="true"
        name="Count"
        :align-by-column="true"
      />
      <DxTotalItem
        column="ID"
        summary-type="count"
        display-format="No. of employees: {0}'"
        name="No. of employees"
      />
      <DxTotalItem column="HireDate" summary-type="count" name="Dates" />
    </DxSummary>
  </DxDataGrid>
</template>

<script>
import DxDataGrid, {
  DxEditing,
  DxColumn,
  DxGroupPanel,
  DxGroupItem,
  DxTotalItem,
  DxFilterRow,
  DxSummary,
} from "devextreme-vue/data-grid";
import DataSource from "devextreme/data/data_source";
import ArrayStore from "devextreme/data/array_store";
import { exportDataGrid } from "devextreme/excel_exporter";
import notify from "devextreme/ui/notify";
import * as ExcelJS from "exceljs";
import { data } from "./data";

const gridRef = "gridRef";

const dataSource = new DataSource({
  store: new ArrayStore({
    data: data,
    key: "ID",
  }),
});

export default {
  name: "App",
  components: {
    DxDataGrid,
    DxEditing,
    DxColumn,
    DxGroupPanel,
    DxGroupItem,
    DxTotalItem,
    DxFilterRow,
    DxSummary,
  },
  data() {
    return {
      dataSource: dataSource,
      gridRef,
      buttons: [
        "edit",
        "delete",
        {
          hint: "Copy row",
          icon: "copy",
          onClick: this.rowCopy,
        },
      ],
    };
  },
  methods: {
    rowCopy(e) {
      let data = e.row.data;
      let str = "";

      for (let prop in data) {
        if (data[prop] !== undefined) {
          str += `${data[prop]}\t`;
        }
      }

      navigator.clipboard.writeText(str).then(() => {
          notify("Row data copied to clipboard.", "success", 500);
      }, () => {
          notify("Row data was not copied. There are insufficient permissions for this action.", "error", 500);
      });
    },
    toolbarCopy(e) {
      e.toolbarOptions.items.push({
          widget: "dxButton",
          location: "after",
          options: {
              hint: "Copy via Export",
              icon: "unselectall",
              onClick: this.copyViaExcelExport
          }
      });
    },
    copyViaExcelExport(e) {
      let workbook = new ExcelJS.Workbook();
      let sheet = workbook.addWorksheet("dummy");
      let str = "";

      let col = this.grid.getVisibleColumns();
      // keep exportable columns and get the last-most column
      col = col.filter((x) => x.dataField !== undefined && x.allowExporting === true);
      let lastColumn = col[col.length - 1].dataField;

      exportDataGrid({
          component: this.grid,
          worksheet: sheet,
          customizeCell: function (options) {
              let { gridCell } = options;
              let field = gridCell.column.dataField;

              switch (gridCell.rowType) {
                  // export header row
                  case "header":
                      str += `${gridCell.column.caption}\t`;
                      break;
                  // export data row
                  case "data":
                      str += `${gridCell.value}\t`;
                      break;
                  // export group row
                  case "group":
                      if (gridCell.value)
                          str += `${field}: ${gridCell.value} `;
                      
                      if (gridCell.groupSummaryItems !== undefined && gridCell.groupSummaryItems.length >= 1) {
                          gridCell.groupSummaryItems.forEach(x => {
                              str += ` ${x.name}: ${x.value} `;
                          });
                      }

                      str += `\t`;

                      break;
                  // export groupFooter & totalFooter. Create a separate switch case if you need different actions (ie different spacing)
                  case "groupFooter":
                  case "totalFooter":
                      str += (gridCell.value === undefined ? `\t` : `${gridCell.totalSummaryItemName}: ${gridCell.value}\t`);

                      break;
                  default:
                      console.log("Unknown row type detected. Please check possible DataGrid breaking changes regarding rowType", gridCell);

                      break;
              }

              if (field === lastColumn) {
                  str += `\r\n`;
              }
          }
      }).then(() => {
          console.log(str);
          navigator.clipboard.writeText(str).then(() => {
              notify("Grid data copied to clipboard.", "success", 500);
          }, () => {
              notify("Grid data was not copied. There are insufficient permissions for this action.", "error", 500);
          });
      });
    }
  },
  computed: {
    grid: function () {
      return this.$refs[gridRef].instance;
    },
  },
};
</script>

<style>
</style>
